server:
  port: 8081
spring:
  application:
    name: book

ribbon:
  eureka:
    enabled: true

foo:
  bar

fizz:
  bang

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
