server:
  port: 8761

eureka:
  enable-self-preservation: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
spring:
  cloud:
    config:
      uri: http://configserver-env.us-east-1.elasticbeanstalk.com
