spring:
  rabbitmq:
      host: daz1e1-rabbitmq-int-vip.sensus-analytics.com
      port: 5672
      username: Labbit
      password: carrot

zuul:
  routes:
    book:
      path: /books/**
      service-id: book
    author:
      path: /authors/**
      service-id: author
    service-instances:
      path: /service-instances/**

ribbon:
  eureka:
    enabled: true

server:
  port: 8080

heart: soul

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaservicedev-env.us-east-1.elasticbeanstalk.com/eureka/
